# Generated by Django 6.0.3 on 2026-03-07 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter agenda title (e.g., युवा सशक्तीकरण)', max_length=200)),
                ('description', models.TextField(help_text='Enter a short description')),
            ],
        ),
    ]
