# Generated by Django 6.0.3 on 2026-03-07 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sonapur', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Example: Teej Program', max_length=200)),
                ('image', models.ImageField(help_text='Upload program photo', upload_to='programs/')),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('guests', models.CharField(help_text='Main guests of the event', max_length=255)),
                ('description', models.TextField(help_text='What was done in the program?')),
            ],
        ),
    ]
