# Generated by Django 6.0.3 on 2026-03-07 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sonapur', '0002_program'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload_cover_page_photo', upload_to='cover_pages/')),
            ],
        ),
    ]
