# Generated by Django 6.0.3 on 2026-03-12 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sonapur', '0004_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description (English)'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Title (English)'),
        ),
    ]
