# Generated by Django 6.0.3 on 2026-03-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sonapur', '0005_agenda_description_en_agenda_title_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description (English)'),
        ),
        migrations.AddField(
            model_name='program',
            name='guests_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Guests (English)'),
        ),
        migrations.AddField(
            model_name='program',
            name='location_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Location (English)'),
        ),
        migrations.AddField(
            model_name='program',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Title (English)'),
        ),
    ]
