# Generated by Django 6.0.3 on 2026-03-12 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sonapur', '0006_program_description_en_program_guests_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name (English)'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='position_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Position (English)'),
        ),
    ]
