# Generated by Django 6.0.3 on 2026-03-16 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sonapur', '0007_teammember_name_en_teammember_position_en'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ne', models.CharField(max_length=200, verbose_name='Name (Nepali)')),
                ('name_en', models.CharField(max_length=200, verbose_name='Name (English)')),
                ('description_ne', models.TextField(verbose_name='Description (Nepali)')),
                ('description_en', models.TextField(verbose_name='Description (English)')),
                ('video_url', models.URLField(help_text='Enter the full YouTube or Vimeo link', max_length=500)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='talents/thumbnails/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Talent',
                'verbose_name_plural': 'Talents',
            },
        ),
    ]
