# Generated by Django 6.0.3 on 2026-03-16 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sonapur', '0008_talent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talent',
            name='video_url',
        ),
        migrations.AddField(
            model_name='talent',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload a video file from your gallery', null=True, upload_to='talents/videos/'),
        ),
    ]
