# Generated by Django 6.0.3 on 2026-03-16 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sonapur', '0009_remove_talent_video_url_talent_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='photo_1',
            field=models.ImageField(blank=True, null=True, upload_to='programs/gallery/'),
        ),
        migrations.AddField(
            model_name='program',
            name='photo_2',
            field=models.ImageField(blank=True, null=True, upload_to='programs/gallery/'),
        ),
        migrations.AddField(
            model_name='program',
            name='photo_3',
            field=models.ImageField(blank=True, null=True, upload_to='programs/gallery/'),
        ),
        migrations.AddField(
            model_name='program',
            name='video_1',
            field=models.FileField(blank=True, null=True, upload_to='programs/videos/'),
        ),
        migrations.AddField(
            model_name='program',
            name='video_2',
            field=models.FileField(blank=True, null=True, upload_to='programs/videos/'),
        ),
        migrations.AddField(
            model_name='program',
            name='video_3',
            field=models.FileField(blank=True, null=True, upload_to='programs/videos/'),
        ),
    ]
