# Generated by Django 6.0.3 on 2026-03-17 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sonapur', '0010_program_photo_1_program_photo_2_program_photo_3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='+977 ', max_length=20)),
                ('email', models.EmailField(default='info@empoweredyouth.org', max_length=254)),
                ('address_ne', models.CharField(max_length=255, verbose_name='Address (Nepali)')),
                ('address_en', models.CharField(max_length=255, verbose_name='Address (English)')),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('tiktok_url', models.URLField(blank=True, null=True)),
                ('google_maps_embed_url', models.TextField(help_text="Paste the 'src' attribute from the Google Maps embed iframe code.")),
            ],
            options={
                'verbose_name': 'Footer Setting',
                'verbose_name_plural': 'Footer Settings',
            },
        ),
    ]
